"""Preserve a run's artifacts before a resubmission writes over them.

Silent failure #14: `run_id` is a hash of the manifest, so it is deliberately identical
across resubmissions -- that is what lets KFP hit its cache, and campaign 07's recovery
depended on a cache hit worth ~7 hours of optimize. But the GCS artifact prefix is keyed on
the *same* value, so the second run of a manifest does not produce a second result set. It
writes over the first.

It is silent in the strongest sense: the pipeline succeeds, the writes succeed, and
`gsutil ls` shows a complete, consistent result set with fresh timestamps. There is no
partial state and no error. Campaign 07 was submitted four times under `run-8a5905dee0` and
only the last survives; the validation arm that the whole campaign was gated on measured
+0.156 safety at 64/64 coverage, and that result is gone.

**Why this runs at submit time rather than re-keying the artifact paths.** The obvious fix
-- give each submission its own prefix -- means threading a per-submission value into the
components that write there. KFP caches on component body hash *and input parameter values*,
so a value that changes every submission gives every component a cache miss forever. That
trades the artifacts for the cache and costs more than the bug.

Snapshotting from the client instead touches **no component at all**: the cache key is
untouched, the live prefix keeps its meaning ("the most recent run"), and prior runs move
somewhere durable before anything can overwrite them. It is the `gsutil -m cp -r` that
`docs/notes/resubmission-investigation.md` prescribes as the manual mitigation, made
automatic so it does not depend on remembering.

Reading an archived run needs no new code: `campaign_floor.fetch_arms` builds
`pipeline-runs/{run_id}/stages/...`, so passing `archive/run-8a5905dee0/20260909T171100Z`
as the run id resolves correctly.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

logger = logging.getLogger(__name__)

ARCHIVE_ROOT = "archive"

# Outputs only. `code.tar.gz` and `manifest.json` are *inputs* -- regenerated by every
# submission and worth nothing after the fact, and the tarball is megabytes. Copying them
# would make every resubmission slower for no recoverable information.
SNAPSHOT_SUBPATHS = ("stages/", "reports/")


def _prior_blobs(bucket: Any, run_id: str) -> list[Any]:
    found = []
    for sub in SNAPSHOT_SUBPATHS:
        found.extend(bucket.list_blobs(prefix=f"pipeline-runs/{run_id}/{sub}"))
    return found


def _stamp(blobs: list[Any]) -> str:
    """Name the snapshot after when the prior run last wrote, not when we archived it.

    `archive/run-x/20260909T175209Z` says which run it was. A snapshot named for the
    moment of archiving says only when someone next pressed submit, which is the less
    useful of the two facts and is already implicit in the ordering.
    """
    times = [t for t in (getattr(b, "updated", None) for b in blobs) if t is not None]
    when = max(times) if times else datetime.now(UTC)
    return when.strftime("%Y%m%dT%H%M%SZ")


def snapshot_prior_run(bucket: Any, run_id: str) -> str | None:
    """Copy any existing artifacts for `run_id` aside. Returns the archive prefix, or None.

    Returns None when there is nothing to preserve -- the first submission of a manifest,
    which is the common case and must stay free.

    Raises on a failed copy rather than continuing. A submission that cannot archive is
    about to destroy results, and a blocked launch is recoverable in a way that overwritten
    measurements are not.
    """
    blobs = _prior_blobs(bucket, run_id)
    if not blobs:
        logger.info("No prior artifacts for %s — nothing to snapshot", run_id)
        return None

    dest_prefix = f"pipeline-runs/{ARCHIVE_ROOT}/{run_id}/{_stamp(blobs)}"

    # Idempotent: a retried submit must not copy twice, and must not fail because the
    # snapshot it would have made already exists.
    if any(bucket.list_blobs(prefix=f"{dest_prefix}/")):
        logger.info("Snapshot already exists at %s — skipping", dest_prefix)
        return dest_prefix

    src_root = f"pipeline-runs/{run_id}/"
    for blob in blobs:
        rel = blob.name[len(src_root) :]
        bucket.copy_blob(blob, bucket, f"{dest_prefix}/{rel}")

    logger.warning(
        "Resubmission of %s: archived %d prior artifact(s) to gs://%s/%s — "
        "the live prefix is about to be overwritten (silent-failures #14)",
        run_id,
        len(blobs),
        getattr(bucket, "name", "?"),
        dest_prefix,
    )
    return dest_prefix
