"""A report you can actually look at.

`experiment_report.md` references its charts relatively (`charts/radar.png`). The PNGs sit
beside it in GCS, but nothing resolves that path: the console does not render markdown, and
downloading the single `.md` gives you seven broken images. The report was unreadable
anywhere except a full local checkout of the folder.

The fix is a **self-contained** HTML sibling with every image inlined as a `data:` URI, so
it has no external references at all and renders identically wherever it is opened —
console preview, a download, an attachment.

These tests pin the properties that make it self-contained, because the failure mode is
silent: a report with a broken `<img src="charts/...">` still opens, still looks like a
report, and is simply missing its evidence.
"""

from __future__ import annotations

import base64
from pathlib import Path  # noqa: TC003 - runtime use in tmp_path fixtures

import pytest

from wrangler.reporting.html_report import (
    MISSING_IMAGE_NOTE,
    render_self_contained_html,
)

# A 1x1 transparent PNG.
_PNG = base64.b64decode(
    b"iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk"
    b"YPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
)


@pytest.fixture
def report_dir(tmp_path: Path) -> Path:
    (tmp_path / "charts").mkdir()
    (tmp_path / "charts" / "radar.png").write_bytes(_PNG)
    return tmp_path


def test_relative_image_becomes_a_data_uri(report_dir: Path):
    html = render_self_contained_html("![Metric Profiles](charts/radar.png)\n", report_dir)
    assert "data:image/png;base64," in html
    assert 'src="charts/radar.png"' not in html


def test_no_external_references_survive(report_dir: Path):
    """The whole point. Any leftover relative src is a broken image somewhere else."""
    md = "\n".join(f"![c{i}](charts/radar.png)" for i in range(5))
    html = render_self_contained_html(md, report_dir)
    assert html.count("data:image/png;base64,") == 5
    assert "charts/" not in html.split("<style>")[-1].split("</style>")[-1] or "src=" not in html


def test_a_missing_chart_is_reported_not_silently_dropped(report_dir: Path):
    """A chart that failed to render must be visible as a gap, not vanish.

    Charts are generated by a step that is allowed to fail without failing the run, so
    "image absent" is a real state. An <img> that silently disappears turns a broken
    pipeline into a report that merely looks shorter.
    """
    html = render_self_contained_html("![Gone](charts/nope.png)\n", report_dir)
    assert MISSING_IMAGE_NOTE in html
    assert "nope.png" in html


def test_tables_render(report_dir: Path):
    md = "| Metric | Delta |\n| --- | --- |\n| safety | +0.16 |\n"
    html = render_self_contained_html(md, report_dir)
    assert "<table>" in html
    assert "<td>safety</td>" in html


def test_details_blocks_survive(report_dir: Path):
    """Optimized prompts ship inside <details>; collapsing must keep working."""
    md = "<details><summary>Prompt</summary>\n\n```\nhello\n```\n\n</details>\n"
    html = render_self_contained_html(md, report_dir)
    assert "<details>" in html
    assert "hello" in html


def test_output_is_a_whole_document_with_inline_styles(report_dir: Path):
    html = render_self_contained_html("# Title\n", report_dir, title="Run 42")
    assert html.lstrip().startswith("<!DOCTYPE html>")
    assert "<style>" in html, "styles must be inline; a stylesheet link is an external ref"
    assert "Run 42" in html


def test_absolute_and_remote_urls_are_left_alone(report_dir: Path):
    """Only local relative paths need rescuing; a real URL already works."""
    html = render_self_contained_html("![x](https://example.com/a.png)\n", report_dir)
    assert 'src="https://example.com/a.png"' in html


def test_path_traversal_outside_the_report_dir_is_refused(tmp_path: Path):
    """`../` must not let a report inline arbitrary files from the container."""
    secret = tmp_path / "secret.png"
    secret.write_bytes(_PNG)
    reports = tmp_path / "reports"
    (reports / "charts").mkdir(parents=True)
    html = render_self_contained_html("![x](../secret.png)\n", reports)
    assert "data:image/png;base64," not in html
    assert MISSING_IMAGE_NOTE in html
